version: '3.8'

services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000
    volumes:
      - ./client:/app
      - /app/node_modules
      - /app/.next
    depends_on:
      - server

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - NODE_ENV=development
      - PORT=8000
      - CLIENT_URL=http://localhost:3000
    env_file:
      - ./server/.env
    volumes:
      - ./server:/app
      - /app/node_modules
      - ./server/temp:/app/temp
      - ./server/logs:/app/logs
      - ./server/preview:/app/preview
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: fluttery
      POSTGRES_USER: fluttery
      POSTGRES_PASSWORD: fluttery_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  redis_data:
  postgres_data: